// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wex.Funding.Infrastructure.Persistence;

namespace Wex.Funding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WexDbContext))]
    partial class WexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wex.Funding.Domain.Cards.Card", c =>
                {
                    c.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    c.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    c.ComplexProperty<Dictionary<string, object>>("CreditLimit", "Wex.Funding.Domain.Cards.Card.CreditLimit#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("credit_limit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("credit_limit_currency");
                        });

                    c.HasKey("Id")
                        .HasName("pk_cards");

                    c.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Wex.Funding.Domain.Transactions.Transaction", t =>
                {
                    t.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    t.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    t.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    t.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    t.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    t.ComplexProperty<Dictionary<string, object>>("Amount", "Wex.Funding.Domain.Transactions.Transaction.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");
                        });

                    t.HasKey("Id")
                        .HasName("pk_transactions");

                    t.HasIndex("CardId")
                        .HasDatabaseName("ix_transactions_card_id");

                    t.HasIndex("CardId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_card_id_date");

                    t.ToTable("transactions", (string)null);
                });
        }
    }
}
